---
- hosts: nodes
  serial: 1
  gather_facts: false
  become: true
  vars:
    restart_nodes: true
  tasks:
    - name: Drain pods from node
      local_action: "command kubectl drain {{ inventory_hostname }} --ignore-daemonsets --force --delete-local-data"
      become: false

    - name: Include maintenance tasks
      include_tasks: "{{item.root}}{{ item.path }}"
      loop: "{{ query('filetree', 'maintenance_tasks/') }}"
      when: item.state == 'file'

    - name: Restart node
      reboot:

    - name: Uncordon node
      local_action: "command kubectl uncordon {{ inventory_hostname }}"
      become: false
